Больше деталей
htmlacademy-javascript/1705477-keksobooking-23 pull request #3
Opened 2021-06-06 14:57 UTC by juliaanto

2021-06-07 13:30 UTC, ademaro requested changes
Почему столько комментариев кода? Вам уже про импорты-экспорты рассказывали?

2021-06-07 13:30 UTC, ademaro commented on js/main.js
> + * @return {*}
а чего типы данных — везде звёздочка?)

2021-06-07 13:30 UTC, ademaro commented on js/main.js
> + */
тут и return есть)

2021-06-07 13:30 UTC, ademaro commented on js/main.js
> +    if (isActiveNumber === '1') {
isActiveNumber — число, а ты сравниваешь со строкой

2021-06-07 15:54 UTC, juliaanto commented on js/main.js
> +    if (isActiveNumber === '1') {
поправила
сначала так сделала, потому что getRandomNumber как оказалось возвращал строку)

2021-06-07 16:25 UTC, ademaro commented on js/main.js
> +    const isActiveNumber = getRandomNumber(0,1);
`const isActiveNumber = Boolean(getRandomNumber(0, 1));`

2021-06-07 16:26 UTC, ademaro commented on js/main.js
> +    author: createAutor(),
```
author: {    
  avatar: `img/avatars/user0${i}.png`,  
}
```

2021-06-10 12:34 UTC, ademaro commented on js/main.js
> +function similarAnnouncements() {
1. функции должны быть с глаголом
2. предлагаю количество объявлений параметризировать

2021-06-10 12:34 UTC, ademaro approved these changes

2021-06-10 12:34 UTC, merged