Помощь друга
htmlacademy-javascript/1705477-keksobooking-23 pull request #9
Opened 2021-07-01 20:21 UTC by juliaanto

2021-07-02 09:41 UTC, ademaro requested changes
Давай подправим) Вечером обсудим детальнее

2021-07-02 09:41 UTC, ademaro commented on js/const.js
> +const addressDigits = 5;
константные значения — капсом

2021-07-02 09:41 UTC, ademaro commented on js/map.js
> +  iconSize: [52, 52],
размеры не те, видимо

2021-07-02 09:41 UTC, ademaro commented on js/map.js
> +mainPinMarker.on('moveend', (evt) => {
moveend можем поменять на move

2021-07-02 09:41 UTC, ademaro commented on js/map.js
> +const SIMILAR_ANNOUNCEMENTS = 10;
константы — в начало модуля

2021-07-02 09:41 UTC, ademaro commented on js/map.js
> +similarAnnouncements.forEach((announcement) => {
расстановка пинов на карту — в отдельную ф-цию

2021-07-02 09:41 UTC, ademaro commented on js/map.js
> +    iconSize: [40, 40],
размер перепроверь и тут

2021-07-04 08:26 UTC, juliaanto commented on js/map.js
> +  iconSize: [52, 52],
размеры из [ТЗ](https://up.htmlacademy.ru/javascript/23/project/keksobooking#keksobooking-5-3), тут сама иконка была не та, поправила

2021-07-04 18:37 UTC, ademaro reviewed
Отлично, летим дальше 🚀

2021-07-04 18:37 UTC, merged